#!/usr/bin/env bash
# Loop forever printing “To infinity and beyond” and trap SIGTERM to loudly declare invincibility
trap 'printf "I am invincible!!!\n" >&2' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
