#!/usr/bin/env bash
# Loop forever printing “To infinity and beyond” and trap SIGTERM to loudly declare invincibility
trap 'echo OK' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
